## Numpy

<b>NumPy</b> (Numerical Python) is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python.

NumPy API is used widely in Pandas, SciPy, Matplotlib, scikit-learn, scikit-image and most other data science and scientific Python packages.

- The NumPy library contains multidimensional array and matrix data structures 
- It provides ndarray, a homogeneous n-dimensional array object
- NumPy is used to perform a wide variety of mathematical operations on arrays basically for ndarray.
- guarantee efficient calculations with arrays and matrices and it supplies an enormous library of high-level mathematical functions

## Content:
- 1. Installing Numpy 
- 2. Why to choose numpy
- 3. Applications of Numpy

### Installing numpy

In [1]:
!pip install python

ERROR: Could not find a version that satisfies the requirement python
ERROR: No matching distribution found for python


### Why to choose numpy

- 1. Numpy arrays are faster(it used fixed type) and compact
- 2. Consumes less memory(store values in contiguous memory location) and convenient to use.
- 3. Used to perform complex mathematical operations on array and matrix

#### Note: 
Since numpy is fixed type i.e., of same data type(like int32, int64) there is no need of type checking.

Let's take an example of a list. There are values of different types, therefore there's a need of type checking making list slower.
```
                                        list = ['a', 1 , 2.5]
                                        a -> string
                                        1 -> int
                                        2.5 -> float
```


### Applications of Numpy
- Mathematics (Scientific calculations)
- Multidimensional array
- Machine learning
- Array generation and manupulation
- Backend for matplotlib, pandas

### Basics of Numpy

In [2]:
# importing numpy
import numpy as np

<b>One Dimesional array

In [3]:
# creating a one dimensional array
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [4]:
# Check dimension 
array1.ndim

1

In [5]:
# Get shape
array1.shape

(3,)

In [6]:
# Check datatype
array1.dtype

dtype('int32')

In [7]:
# Get datatype memory size in bytes
array1.itemsize

4

In [8]:
# Get number of elements in array
array1.size

3

In [9]:
# Get total memory size of array based on data items
array1.nbytes

12

<b>Two Dimensional array

In [10]:
# creating a two dimensional array
array2 = np.array([[1,2,3,4],[5,6,7,8]])
array2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
# Check dimension
array2.ndim

2

In [12]:
# Get shape
array2.shape

(2, 4)

In [13]:
# check datatype
array2.dtype

dtype('int32')

In [14]:
# Get datatype memory size in bytes
array2.itemsize

4

In [15]:
# Get number of elements in array
array2.size

8

In [16]:
# Get total memory size of array based on data items
array2.nbytes

32

<b>Three Dimensional array

In [17]:
#creating a three dimensional array
array3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])
array3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [18]:
# Check dimension
array3.ndim

3

In [19]:
# Get shape
array3.shape

(1, 3, 4)

In [20]:
# check datatype
array3.dtype

dtype('int32')

In [21]:
# Get datatype memory size in bytes
array3.itemsize

4

In [22]:
# Get number of elements in array
array3.size

12

In [23]:
# Get total memory size of array based on data items
array3.nbytes

48

### Datatypes in numpy

### Integer type

In [24]:
arr = np.array([1,2,3],dtype='int32')

print('## Dataype: ',arr.dtype)
print("Datatype size for each element of the array: ",arr.itemsize)
print("Memory size of arr: ",arr.nbytes)

## Dataype:  int32
Datatype size for each element of the array:  4
Memory size of arr:  12


In [25]:
arr = np.array([1,2,3],dtype='int8')

print('## Dataype: ',arr.dtype)
print("Datatype size for each element of the array: ",arr.itemsize)
print("Memory size of arr: ",arr.nbytes)

## Dataype:  int8
Datatype size for each element of the array:  1
Memory size of arr:  3


In [26]:
arr = np.array([1,2,3],dtype='int16')

print('## Dataype: ',arr.dtype)
print("Datatype size for each element of the array: ",arr.itemsize)
print("Memory size of arr: ",arr.nbytes)

## Dataype:  int16
Datatype size for each element of the array:  2
Memory size of arr:  6


### Float type

In [27]:
arr1 = np.array([1,2,3],dtype='float32')

print(arr1)
print('## Dataype: ',arr1.dtype)
print("Datatype size for each element of the array: ",arr1.itemsize)
print("Memory size of arr: ",arr1.nbytes)

[1. 2. 3.]
## Dataype:  float32
Datatype size for each element of the array:  4
Memory size of arr:  12


In [28]:
arr1 = np.array([2.0,5.6,6.0],dtype='float16')

print(arr1)
print('## Dataype: ',arr1.dtype)
print("Datatype size for each element of the array: ",arr1.itemsize)
print("Memory size of arr: ",arr1.nbytes)

[2.  5.6 6. ]
## Dataype:  float16
Datatype size for each element of the array:  2
Memory size of arr:  6


<b>NOTE:</b> You can see we how changing from int8, int16, int32 and float32, float16 changes the size of dataitems. This is also one of the property why numpy is faster in speed and can be used according to our memory availability and requirement. Changing the int32 to int16 and int8 reduces the size of the dataitems and the whole array. And also changing int8 to int16 and int32 increases the memory of the array.

### Create an array with a range of elements

In [29]:
np.arange(4)

array([0, 1, 2, 3])

In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.arange(start,stop,step)

In [31]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

### linspace: Create an array with a range of elements linearly spaced

In [32]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [33]:
np.linspace([0,1],[10,20],num=5) # default axis = 0

array([[ 0.  ,  1.  ],
       [ 2.5 ,  5.75],
       [ 5.  , 10.5 ],
       [ 7.5 , 15.25],
       [10.  , 20.  ]])

- axis 0 : column
- axis 1: row

In [34]:
np.linspace([0,1],[10,20],num=5,axis=1)

array([[ 0.  ,  2.5 ,  5.  ,  7.5 , 10.  ],
       [ 1.  ,  5.75, 10.5 , 15.25, 20.  ]])

### Create an array with only zeros

In [35]:
np.zeros(3)

array([0., 0., 0.])

In [36]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [37]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [38]:
np.zeros((2,3,3)).ndim

3

### Create an array with only ones

In [39]:
np.ones(4)

array([1., 1., 1., 1.])

In [40]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [41]:
np.ones((2,2),dtype='int32')

array([[1, 1],
       [1, 1]])

### Reshaping an array

In [42]:
np.arange(16).reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [44]:
arr.reshape((1,3,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [45]:
arr.reshape((1,3,4)).ndim

3

In [46]:
arr.reshape((4,3))
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### Resizing an array

In [47]:
arr = np.arange(12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [48]:
arr.resize((4,3))

In [49]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

<b>Difference between reshape and resize</b>
- resize change the shape of array itself
- reshape array does not change the shape of the array itself. The reshaped array need to be save in another variable to save changes

### Array Indexing and Slicing

In [54]:
array = np.arange(1,15).reshape((2,7))
array

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

GET a specific element in array ``` [row,column] ```

In [56]:
array[1,4]

12

In [57]:
array[0,6]

7

<b># Get a specific row

In [58]:
print("0th row")
array[0,:]

0th row


array([1, 2, 3, 4, 5, 6, 7])

In [59]:
print("1st row")
array[1,:]

1st row


array([ 8,  9, 10, 11, 12, 13, 14])

<b># Get a specific column

In [64]:
print('Coulmn 1')
array[:,1]

Coulmn 1


array([2, 9])

In [66]:
print('column 4th')
array[:,4].reshape((2,1))

column 4th


array([[ 5],
       [12]])

``` [startindex: endindex: stepsize] ```

In [73]:
print(array)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [81]:
array[0,1:6:2]

array([2, 4, 6])

Explanation: [0,1:6:2]
0 th row,
1st element/index to 6th elements/index
step by 2

```[0th row, start from 1st index : go till 6th index : while taking a jump/step of 2 elements/index]```

In [83]:
arr = np.arange(40).reshape(4,10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [84]:
arr[2,1:8]

array([21, 22, 23, 24, 25, 26, 27])

In [86]:
# Taking a step of 2
arr[2,1:8:2]

array([21, 23, 25, 27])

In [88]:
arr = np.arange(32).reshape((2,16))
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]])

<b>-1 : denotes the last index

In [90]:
arr[0,3:-1:2]

array([ 3,  5,  7,  9, 11, 13])

### Changing array elements using index and slices

In [94]:
# lets create an (2,7) array with all zeros
array1 = np.zeros((2,7))
print(array1)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


<b>Changing elements

In [95]:
array1[0,4] = 1
print(array1)

[[0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [96]:
array1[1,3]= 20
print(array1)

[[ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0. 20.  0.  0.  0.]]


<b>Changing a series of elements

In [98]:
array1

array([[ 0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0., 20.,  0.,  0.,  0.]])

In [99]:
array1[0,1:-1] = 22
print(array1)

[[ 0. 22. 22. 22. 22. 22.  0.]
 [ 0.  0.  0. 20.  0.  0.  0.]]


#### Example with 3D array