## 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'1.18.1'

#### 3. Create a null vector of size 10 (★☆☆)
```hints: np.zeors```

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [4]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
print('Size/ length of arr: ',arr.size)

Size/ length of arr:  10


In [6]:
print('m/m of one item: ',arr.itemsize)

m/m of one item:  4


In [7]:
print('m/m of whole arr: ',arr.itemsize)

m/m of whole arr:  4


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)
```hint: np.info(object)```

In [8]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [9]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [10]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [11]:
arr = np.arange(10)
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [12]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
```hint: np.nonzero()```

In [13]:
arr = np.array([1,2,0,0,4,0])
arr.nonzero()

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

- using np.identity()

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- using np.eye()

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

- 1st way rand

In [16]:
np.random.rand(3,3,3)

array([[[0.88600502, 0.90463816, 0.0796619 ],
        [0.37319511, 0.76084838, 0.09942474],
        [0.77250075, 0.74059848, 0.10127627]],

       [[0.26368689, 0.51261954, 0.68950125],
        [0.50251697, 0.69566672, 0.86313317],
        [0.7570692 , 0.66526536, 0.96395811]],

       [[0.87646653, 0.87408544, 0.67273701],
        [0.56684287, 0.89669398, 0.45195894],
        [0.84456772, 0.20986258, 0.27825245]]])

- 2nd way random

In [17]:
np.random.random((3,3,3))

array([[[0.02203186, 0.04436927, 0.67005518],
        [0.75449203, 0.78715389, 0.34890553],
        [0.31802393, 0.29157272, 0.25251411]],

       [[0.07155567, 0.8973218 , 0.33510258],
        [0.07161332, 0.50190964, 0.39863233],
        [0.85341702, 0.76059424, 0.33959678]],

       [[0.34870271, 0.94815701, 0.66228771],
        [0.27353656, 0.10368117, 0.0832584 ],
        [0.80972666, 0.3768278 , 0.67876173]]])

- 3rd way randn

In [18]:
np.random.randn(3,3,3)

array([[[ 1.05350047,  0.51387784,  0.75865163],
        [ 0.92474519,  2.41661156,  0.22139289],
        [-0.40013854, -1.68482658, -1.05457201]],

       [[-1.16708115,  0.06582916,  0.48013291],
        [ 0.0083488 ,  0.45414471, -0.43807871],
        [-2.64961619, -0.89969137, -0.16046062]],

       [[-0.13404873, -0.76573245, -0.5509204 ],
        [ 0.40379074, -0.45111133, -0.25472121],
        [-0.90986147,  1.20297162,  1.21964194]]])

- 4th way randint

In [19]:
np.random.randint(0,10,size=(3,3,3))

array([[[3, 7, 4],
        [6, 8, 6],
        [0, 8, 1]],

       [[5, 5, 3],
        [1, 1, 0],
        [2, 4, 1]],

       [[3, 3, 4],
        [7, 5, 6],
        [5, 5, 2]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [20]:
arr = np.random.random(size=(10,10))

In [21]:
print("arr min: ",np.min(arr))

arr min:  0.005358122259019438


In [22]:
print("arr max: ",np.max(arr))

arr max:  0.9851180604733679


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [23]:
arr = np.random.random(size=30)
print("arr mean: ",np.mean(arr))

arr mean:  0.5314464315335061


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [24]:
arr1 = np.ones((5,5))
arr1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
arr2 = np.zeros((3,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
arr1[1:-1,1:-1] = arr2

In [27]:
arr1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)
```hint: np.pad(array, pad_width)```

In [28]:
arr = np.arange(1,17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [29]:
np.pad(arr,pad_width=1)

array([[ 0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  0],
       [ 0,  5,  6,  7,  8,  0],
       [ 0,  9, 10, 11, 12,  0],
       [ 0, 13, 14, 15, 16,  0],
       [ 0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

<b>Answers: </b>
```python
0 * np.nan -> nan
np.nan == np.nan -> False
np.inf > np.nan -> False
np.nan - np.nan -> nan
np.nan in set([np.nan]) -> True
0.3 == 3 * 0.1 -> False (Special case = 0.30000000000000004)
    
```

In [30]:
0*np.nan

nan

In [31]:
np.nan == np.nan

False

In [32]:
np.inf > np.nan

False

In [33]:
np.nan - np.nan

nan

In [34]:
np.nan in set([np.nan])

True

In [35]:
0.3 == 3*0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
```hint: np.diag()```

In [36]:
np.diag([1,2,3,4],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [37]:
arr = np.zeros((8,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
arr[1::2,::2] = 1
arr[::2,1::2] = 1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
```np.unravel_index```

In [39]:
np.unravel_index(99,shape=(7,6,8))

(2, 0, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

- 1st way

In [40]:
arr = np.tile([[0,1,0,1,0,1,0,1],[1,0,1,0,1,0,1,0]], reps=(4,1))
print(arr.shape)

(8, 8)


In [41]:
arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

- 2nd way

In [42]:
print(np.tile([[0,1],[1,0]], reps = (4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [43]:
arr = np.arange(25).reshape((5,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [44]:
mean = np.mean(arr)
std = np.std(arr)

print("Norm of arr: ")
(arr - mean)/std

Norm of arr: 


array([[-1.66410059, -1.52542554, -1.38675049, -1.24807544, -1.10940039],
       [-0.97072534, -0.83205029, -0.69337525, -0.5547002 , -0.41602515],
       [-0.2773501 , -0.13867505,  0.        ,  0.13867505,  0.2773501 ],
       [ 0.41602515,  0.5547002 ,  0.69337525,  0.83205029,  0.97072534],
       [ 1.10940039,  1.24807544,  1.38675049,  1.52542554,  1.66410059]])