In [1]:
import numpy as np

### Linear algebra stuffs with numpy
- Determinant
- Rank of matrix
- Eigen Value
- Inverse of a matrix
- Trace
- Singular Vector Decomposition
- Matrix Norm
- Matrix Power
- Dot product of array
- Dor product of vector
- Inner product
- Outer product

In [2]:
# Fing the determinant
a = np.identity(3)
np.linalg.det(a)

1.0

Determinant of identity matrix is 1

<b>Rank of matrix: </b> we calculate the rank of matrix to check for number of unique solutions possible

```


|1  2 -2|   Form 0's in the following pos  |1 2 -2|    Form 0's in |1 2 -2|
|2  3  4|                ----->            |0 x  y|     ------>    |0 x  y|
|2  5  7|                                  |0 a  b|                |0 0  b|


Remember the R2 -> something
             R3 -> something 
             
             we learnt in school to make zeros
```

In [6]:
# Rank of matrix
I = np.eye(3)
np.linalg.matrix_rank(I)

3

In [7]:
np.linalg.matrix_rank(np.zeros((4,1)))

0

In [8]:
np.linalg.matrix_rank(np.ones((4,1)))

1

In [10]:
np.linalg.matrix_rank(np.full((4,3),fill_value=[1,2,3]))

1

In [16]:
np.arange(16).reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [17]:
np.linalg.matrix_rank(np.arange(16).reshape((4,4)))

2

<b>Power of matrix: </b>To calculate the power of a matrix ```A``` we multiply by itself for ```n``` number of times the power we needed.

```np.linalg.matrix_power()```

In [28]:
# Exercise 1
arr = np.array([[4,-5],[4,-5]])
arr

array([[ 4, -5],
       [ 4, -5]])

In [31]:
np.linalg.matrix_power(arr,2)

array([[-4,  5],
       [-4,  5]])

In [32]:
# Exercise 2
arr = np.array([[1,-3],[2,5]])
arr

array([[ 1, -3],
       [ 2,  5]])

In [33]:
arr_2 = np.linalg.matrix_power(arr,2)

In [34]:
arr_2

array([[ -5, -18],
       [ 12,  19]])

In [36]:
np.linalg.matrix_power(arr,3)

array([[-41, -75],
       [ 50,  59]])

<b>Inverse of matrix: </b> muliplicative inverse

The inverse of A is A<sup>-1</sup> only when:

- like
   - A × A<sup>-1</sup> = A<sup>-1</sup> × A = I
- or
    - AX = B which is equivalent to X = A<sup>-1</sup>B

Sometimes there is no inverse at all if determinant = 0.

<b>How to calculate matrix multiplicative inverse</b>

- 1. calculating the Matrix of Minors,
- 2. then turn that into the Matrix of Cofactors,
- 3. then the Adjugate, and
- 4. multiply that by 1/Determinant.

<b>Refs: </b>https://www.mathsisfun.com/algebra/matrix-inverse-minors-cofactors-adjugate.html

In [37]:
arr = np.array([[1,-3],[2,5]])
arr

array([[ 1, -3],
       [ 2,  5]])

In [38]:
np.linalg.inv(arr)

array([[ 0.45454545,  0.27272727],
       [-0.18181818,  0.09090909]])

In [40]:
arr1 = np.array([[3,0,2],[2,0,-2],[0,1,1]])
arr1

array([[ 3,  0,  2],
       [ 2,  0, -2],
       [ 0,  1,  1]])

In [41]:
np.linalg.inv(arr1)

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])

<b>Matrix Norm: </b>

In [42]:
np.linalg.norm(arr1)

4.795831523312719