In [1]:
import numpy as np

### Different types of matrix
    - Remaining
- Identity
- eye
- repeat (repeating copies)
- copy (copying)

<b>np.identity()

In [2]:
np.identity(3,dtype='int32')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

<b>np.eye()

In [3]:
np.eye(N=3, dtype='int32')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
# M = columns
np.eye(N=3, M=1, dtype='int32')

array([[1],
       [0],
       [0]])

<b>np.repeat()

In [5]:
arr = np.arange(4)
arr

array([0, 1, 2, 3])

In [6]:
np.repeat(arr, repeats=2)

array([0, 0, 1, 1, 2, 2, 3, 3])

In [7]:
arr = np.array([[1,2,3]])
arr

array([[1, 2, 3]])

In [8]:
np.repeat(arr, repeats=3,axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [9]:
np.repeat(arr, repeats=3,axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

<b>np.copy()

In [10]:
arr = np.identity(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
arr1 = np.copy(arr)
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<b>Question

<b><center>Create a Numpy matrix like this</center><br>

<table>
    <tr>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
    </tr>
    <tr>
        <td>1</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
    </tr>
    <tr>
        <td>1</td>
        <td>0</td>
        <td>9</td>
        <td>0</td>
        <td>1</td>
    </tr>
    <tr>
        <td>1</td>
        <td>0</td>
        <td>0</td>
        <td>0</td>
        <td>1</td>
    </tr>
    <tr>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
        <td>1</td>
    </tr>
</table>

<b>Solution

In [12]:
arr1 = np.ones((5,5))
arr1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
arr2 = np.zeros((3,3))
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
arr2[1,1] = 9
arr2

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [15]:
arr1[1:-1,1:-1] = arr2
arr1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

### NOTE: Be careful when copying arrays!!!

In [16]:
a = np.array([1,2,3])
b = a
print(b)

[1 2 3]


In [17]:
b[0] = 50
b

array([50,  2,  3])

In [18]:
a

array([50,  2,  3])

As you can see when we copied array a in b, by just assigning b = a,
the changes made in b also reflect changes in a

In [19]:
a[1] = -50
a

array([ 50, -50,   3])

In [20]:
b

array([ 50, -50,   3])

Same thing happens with b when we make changes in a it also reflects in b. 

<b>REASON: </b>So what is happening here is that we have copied the array but the address remains the same for both the arrays ```a``` and ```b```

In [21]:
a = np.array([1,2,3])
b = np.copy(a)
b

array([1, 2, 3])

In [22]:
b[0] = 50
b

array([50,  2,  3])

In [23]:
a

array([1, 2, 3])

Now we can see that the same effect that we saw earlier is now not the same. We have made a complete new array ```b``` by deep copying ```a```

## Mathematics with numpy

In [24]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [25]:
a + 1

array([2, 3, 4, 5])

In [26]:
a - 2

array([-1,  0,  1,  2])

In [27]:
a * 2

array([2, 4, 6, 8])

In [28]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [29]:
a += 2
a

array([3, 4, 5, 6])

<b>NOTE: </b>python has a really good thing with it broadcasting. Broadcasting as the name says the operation is broadcasted to all the elements in the array

In [30]:
b = np.array([1,2,3,4])
b

array([1, 2, 3, 4])

In [31]:
b ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [32]:
b ** 3

array([ 1,  8, 27, 64], dtype=int32)

In [33]:
# Take the sine of all values
np.sin(b)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [34]:
# cosine
np.cos(b)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [35]:
# standard deviation
np.std(b)

1.118033988749895

In [36]:
# mean
np.mean(b)

2.5

In [37]:
# median
np.median(b)

2.5

<b>Vander Funtion</b>
Will explain in later modules

In [38]:
np.vander(b)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [39]:
# variance
np.var(b)

1.25

In [40]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [41]:
a - b

array([-4, -4, -4, -4])

In [42]:
a * b

array([ 5, 12, 21, 32])

In [43]:
a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [44]:
a % b

array([1, 2, 3, 4], dtype=int32)

In [45]:
a // b

array([0, 0, 0, 0], dtype=int32)

In [46]:
a ** b

array([    1,    64,  2187, 65536], dtype=int32)

### Linear Algebra
```np.linalg()```

#### Matrix Multiplication

In [47]:
a = np.ones((2,3))
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [48]:
b = np.full((3,2),fill_value=2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

```python
(3 , 2) * (2 , 3) = (3 , 3) 

```

In [49]:
# matrix multiplication
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

#### Other linear algebra stuffs with numpy
- Determinant
- Rank of matrix
- Eigen Value
- Inverse of a matrix
- Trace
- Singular Vector Decomposition
- Matrix Norm
- Matrix Power
- Dot product of array
- Dor product of vector
- Inner product
- Outer product

Refs: https://numpy.org/doc/stable/reference/routines.linalg.html

In [50]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

Determinant of identity matrix is ```1```