In [1]:
import numpy as np

### Statistics

In [2]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

```np.min(a,axis)```

In [3]:
np.min(stats)

1

In [4]:
np.min(stats,axis=1)

array([1, 4])

In [5]:
np.min(stats,axis=0)

array([1, 2, 3])

```np.max(a,axis)```

In [6]:
np.max(stats)

6

In [8]:
np.max(stats,axis=1)

array([3, 6])

In [9]:
np.max(stats,axis=0)

array([4, 5, 6])

- np.mean(a,axis)
- np.median(a,axis)
- np.sum(a,axis)

### Reorganizing Arrays

In [13]:
before = np.arange(1,9).reshape((2,4))
before.shape

(2, 4)

In [14]:
after = before.reshape((8,1))
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

### Vertically stacking vectors
```np.vstack()```

In [15]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
np.vstack((v1,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

We can keep copying on or stacking vectors also

In [17]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

### Horizontally stacking vectors
```np.hstack()```

In [21]:
h1 = np.zeros((2,4))
h2 = np.ones((2,2))

np.hstack([h1,h2])

array([[0., 0., 0., 0., 1., 1.],
       [0., 0., 0., 0., 1., 1.]])

In [22]:
np.hstack([h1,h2,h1])

array([[0., 0., 0., 0., 1., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 1., 0., 0., 0., 0.]])

## Miscellaneous

#### Load data from file

In [25]:
file_data = np.genfromtxt('data.txt',delimiter=',', dtype='int32')
file_data

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

<b>astype()</b>

In [26]:
data = np.genfromtxt('data.txt',delimiter=',')
data = data.astype('int32')
data

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

### Boolean Masking and Advanced Indexing

In [29]:
data > 10

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
         True],
       [False, False, False, False, False,  True,  True,  True,  True,
         True]])

In [30]:
data[data>10]

array([12, 14, 16, 18, 11, 13, 15, 17, 19])

You can index with a list in Numpy i.e, you can specify values in a list that will act as
an index and retrieve the values at that index. Let's see an example for better understanding

In [33]:
## You can index with a list in Numpy
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[[1,2,6]]

array([2, 3, 7])

In [32]:
arr[[1,2,-1]]

array([2, 3, 9])

### np.any()
```np.any(a,axis)``` Checks if there's any value like

In [35]:
np.any(data>10)

True

In [36]:
np.any(data>10,axis=0)

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [40]:
np.any(data>10,axis=1)

array([False,  True,  True])

### np.all()
```np.all(a,axis)``` Checks if all the values satisfy some conditions

In [45]:
np.all(data>10)

False

In [44]:
np.all(data>10,axis=0)

array([False, False, False, False, False, False, False, False, False,
       False])

In [43]:
np.all(data>10,axis=1)

array([False, False, False])

### Doing some more practice

In [46]:
data

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

In [55]:
((data>10) & (data<15))

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True, False,
        False],
       [False, False, False, False, False,  True,  True, False, False,
        False]])

In [53]:
data[((data>10) & (data<15))]

array([12, 14, 11, 13])

In [54]:
data[~((data>10) & (data<15))]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10,  0,  2,  4,  6,  8, 10, 16,
       18,  1,  3,  5,  7,  9, 15, 17, 19])

You can specify some constraints or conditions or some expressions to extract some values
from our dataset

### Questions

In [57]:
arr = np.arange(1,31).reshape((6,5))
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [59]:
# Q1. Get the value of elements above the daigonal
np.diag(arr,k=1)

array([ 2,  8, 14, 20])

In [61]:
# This can also be done advance indexing by passing the index within the arr
arr[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

We specify the arr that we need values from [0,1,2,3] rows and [1,2,3,4] columns

In [60]:
# Q2. Get [[11,12],[16,17]] from the above arr
arr[2:4,:2]

array([[11, 12],
       [16, 17]])

In [78]:
# Q3. Get values [[4,5],[24,25],[29,30]]
arr[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [76]:
a = arr[[0,4,5]][:,3:]
a

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [77]:
a = arr[[0,4,5]]
a[:,3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])