In [1]:
import numpy as np

<b>horizonatal split</b>

```np.hsplit()```

In [2]:
arr = np.arange(30).reshape(2,15)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [3]:
res = np.hsplit(arr,3)
res

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [4]:
res[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [5]:
res[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [6]:
res[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

<b>vertical split</b>

```np.vsplit()```

In [7]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [8]:
res = np.vsplit(arr,2)
res

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [9]:
res[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [10]:
res[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

<b>Flattern Array</b>

```np.flatten()```

In [11]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [12]:
# conventional way
for row in a:
    for col in row:
        print(col)

0
1
2
3
4
5
6
7
8
9
10
11


In [13]:
# Using numpy flatten function
f = a.flatten()
f.shape

(12,)

In [14]:
for e in f:
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11


![alt text](order_c_and_f_numpy.JPG)

<b>Iterating arr using</b>

```np.nditer(a,order)```

In [15]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### order = "C"

In [16]:
for e in np.nditer(a,order='C'):
    print(e)

0
1
2
3
4
5
6
7
8
9
10
11


#### order = "F"

In [17]:
for e in np.nditer(a,order="F"):
    print(e)

0
4
8
1
5
9
2
6
10
3
7
11


In [18]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [19]:
for e in np.nditer(a,order="F"):
    print(e)

0
4
8
1
5
9
2
6
10
3
7
11


In [20]:
for e in np.nditer(a,order="F",flags = ['external_loop']):
    print(e)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]
